// Sample data for diamonds and gemstones
// In production, this would be fetched from Shopify API or a custom backend

export const sampleDiamonds = [
  {
    id: 'D001',
    shape: 'round',
    carat: 0.30,
    color: 'K',
    clarity: 'SI2',
    cut: 'Excellent',
    polish: 'Excellent',
    symmetry: 'Very Good',
    fluorescence: 'None',
    certification: 'GIA',
    price: 249,
    currency: '€',
    lwRatio: 1.0,
    image: null,
    reportNumber: 'GIA2234567890'
  },
  {
    id: 'D002',
    shape: 'round',
    carat: 0.30,
    color: 'K',
    clarity: 'SI1',
    cut: 'Excellent',
    polish: 'Excellent',
    symmetry: 'Very Good',
    fluorescence: 'None',
    certification: 'GIA',
    price: 281,
    currency: '€',
    lwRatio: 1.0,
    image: null,
    reportNumber: 'GIA2234567891'
  },
  {
    id: 'D003',
    shape: 'round',
    carat: 0.35,
    color: 'L',
    clarity: 'SI1',
    cut: 'Excellent',
    polish: 'Excellent',
    symmetry: 'Very Good',
    fluorescence: 'None',
    certification: 'IGI',
    price: 291,
    currency: '€',
    lwRatio: 1.0,
    image: null,
    reportNumber: 'IGI447891234'
  },
  {
    id: 'D004',
    shape: 'round',
    carat: 0.30,
    color: 'J',
    clarity: 'SI1',
    cut: 'Excellent',
    polish: 'Excellent',
    symmetry: 'Very Good',
    fluorescence: 'None',
    certification: 'GIA',
    price: 293,
    currency: '€',
    lwRatio: 1.0,
    image: null,
    reportNumber: 'GIA2234567892'
  },
  {
    id: 'D005',
    shape: 'round',
    carat: 0.30,
    color: 'K',
    clarity: 'SI2',
    cut: 'Excellent',
    polish: 'Excellent',
    symmetry: 'Excellent',
    fluorescence: 'None',
    certification: 'IGI',
    price: 299,
    currency: '€',
    lwRatio: 1.0,
    image: null,
    reportNumber: 'IGI447891235'
  },
  {
    id: 'D006',
    shape: 'oval',
    carat: 0.50,
    color: 'F',
    clarity: 'VS1',
    cut: 'Excellent',
    polish: 'Excellent',
    symmetry: 'Excellent',
    fluorescence: 'None',
    certification: 'GIA',
    price: 1250,
    currency: '€',
    lwRatio: 1.35,
    image: null,
    reportNumber: 'GIA2234567893'
  },
  {
    id: 'D007',
    shape: 'cushion',
    carat: 0.75,
    color: 'G',
    clarity: 'VS2',
    cut: 'Very Good',
    polish: 'Excellent',
    symmetry: 'Very Good',
    fluorescence: 'Faint',
    certification: 'GIA',
    price: 1890,
    currency: '€',
    lwRatio: 1.05,
    image: null,
    reportNumber: 'GIA2234567894'
  },
  {
    id: 'D008',
    shape: 'princess',
    carat: 1.0,
    color: 'H',
    clarity: 'VVS2',
    cut: 'Ideal',
    polish: 'Excellent',
    symmetry: 'Excellent',
    fluorescence: 'None',
    certification: 'GIA',
    price: 4500,
    currency: '€',
    lwRatio: 1.0,
    image: null,
    reportNumber: 'GIA2234567895'
  },
  {
    id: 'D009',
    shape: 'emerald',
    carat: 1.25,
    color: 'E',
    clarity: 'VVS1',
    cut: 'Excellent',
    polish: 'Excellent',
    symmetry: 'Excellent',
    fluorescence: 'None',
    certification: 'GIA',
    price: 8900,
    currency: '€',
    lwRatio: 1.45,
    image: null,
    reportNumber: 'GIA2234567896'
  },
  {
    id: 'D010',
    shape: 'pear',
    carat: 0.80,
    color: 'D',
    clarity: 'IF',
    cut: 'Excellent',
    polish: 'Excellent',
    symmetry: 'Excellent',
    fluorescence: 'None',
    certification: 'GIA',
    price: 6200,
    currency: '€',
    lwRatio: 1.55,
    image: null,
    reportNumber: 'GIA2234567897'
  },
  {
    id: 'D011',
    shape: 'marquise',
    carat: 0.65,
    color: 'F',
    clarity: 'VS1',
    cut: 'Very Good',
    polish: 'Excellent',
    symmetry: 'Very Good',
    fluorescence: 'Medium',
    certification: 'IGI',
    price: 2100,
    currency: '€',
    lwRatio: 2.0,
    image: null,
    reportNumber: 'IGI447891236'
  },
  {
    id: 'D012',
    shape: 'asscher',
    carat: 1.5,
    color: 'G',
    clarity: 'VS2',
    cut: 'Excellent',
    polish: 'Excellent',
    symmetry: 'Excellent',
    fluorescence: 'None',
    certification: 'GIA',
    price: 7500,
    currency: '€',
    lwRatio: 1.02,
    image: null,
    reportNumber: 'GIA2234567898'
  },
  {
    id: 'D013',
    shape: 'radiant',
    carat: 2.0,
    color: 'H',
    clarity: 'SI1',
    cut: 'Very Good',
    polish: 'Very Good',
    symmetry: 'Very Good',
    fluorescence: 'Faint',
    certification: 'GIA',
    price: 12000,
    currency: '€',
    lwRatio: 1.25,
    image: null,
    reportNumber: 'GIA2234567899'
  },
  {
    id: 'D014',
    shape: 'heart',
    carat: 0.90,
    color: 'E',
    clarity: 'VVS2',
    cut: 'Excellent',
    polish: 'Excellent',
    symmetry: 'Excellent',
    fluorescence: 'None',
    certification: 'GIA',
    price: 5800,
    currency: '€',
    lwRatio: 1.0,
    image: null,
    reportNumber: 'GIA2234567900'
  },
  {
    id: 'D015',
    shape: 'round',
    carat: 3.0,
    color: 'D',
    clarity: 'FL',
    cut: 'Ideal',
    polish: 'Excellent',
    symmetry: 'Excellent',
    fluorescence: 'None',
    certification: 'GIA',
    price: 149160,
    currency: '€',
    lwRatio: 1.0,
    image: null,
    reportNumber: 'GIA2234567901'
  }
];

export const sampleGemstones = [
  {
    id: 'G001',
    type: 'natural',
    gemstoneType: 'emerald',
    shape: 'oval',
    carat: 0.53,
    color: 'Green',
    intensity: 'vivid',
    clarity: 'v1',
    certification: 'ICL',
    price: 545,
    currency: '€',
    image: null,
    reportNumber: 'ICL123456'
  },
  {
    id: 'G002',
    type: 'natural',
    gemstoneType: 'emerald',
    shape: 'oval',
    carat: 1.75,
    color: 'Green',
    intensity: 'vivid',
    clarity: 'v2',
    certification: 'ICL',
    price: 500,
    currency: '€',
    image: null,
    reportNumber: 'ICL123457'
  },
  {
    id: 'G003',
    type: 'natural',
    gemstoneType: 'emerald',
    shape: 'pear',
    carat: 2.91,
    color: 'Green',
    intensity: 'intense',
    clarity: 'i1',
    certification: 'ICL',
    price: 550,
    currency: '€',
    image: null,
    reportNumber: 'ICL123458'
  },
  {
    id: 'G004',
    type: 'natural',
    gemstoneType: 'emerald',
    shape: 'cushion',
    carat: 1.26,
    color: 'Green',
    intensity: 'medium',
    clarity: 'i2',
    certification: 'ICL',
    price: 552,
    currency: '€',
    image: null,
    reportNumber: 'ICL123459'
  },
  {
    id: 'G005',
    type: 'natural',
    gemstoneType: 'sapphire',
    shape: 'round',
    carat: 1.20,
    color: 'Blue',
    intensity: 'vivid',
    clarity: 'ec1',
    certification: 'GRS',
    price: 2500,
    currency: '€',
    image: null,
    reportNumber: 'GRS789012'
  },
  {
    id: 'G006',
    type: 'natural',
    gemstoneType: 'ruby',
    shape: 'oval',
    carat: 1.05,
    color: 'Red',
    intensity: 'vivid',
    clarity: 'ec1',
    certification: 'GRS',
    price: 8500,
    currency: '€',
    image: null,
    reportNumber: 'GRS789013'
  },
  {
    id: 'G007',
    type: 'natural',
    gemstoneType: 'tanzanite',
    shape: 'cushion',
    carat: 3.50,
    color: 'Blue-Violet',
    intensity: 'deep',
    clarity: 'ec1',
    certification: 'ICL',
    price: 3200,
    currency: '€',
    image: null,
    reportNumber: 'ICL123460'
  },
  {
    id: 'G008',
    type: 'natural',
    gemstoneType: 'morganite',
    shape: 'oval',
    carat: 4.25,
    color: 'Pink',
    intensity: 'light',
    clarity: 'ec1',
    certification: 'ICL',
    price: 1800,
    currency: '€',
    image: null,
    reportNumber: 'ICL123461'
  },
  {
    id: 'G009',
    type: 'natural',
    gemstoneType: 'aquamarine',
    shape: 'emerald',
    carat: 5.00,
    color: 'Blue',
    intensity: 'light',
    clarity: 'ec1',
    certification: 'ICL',
    price: 2200,
    currency: '€',
    image: null,
    reportNumber: 'ICL123462'
  },
  {
    id: 'G010',
    type: 'lab',
    gemstoneType: 'sapphire',
    shape: 'round',
    carat: 2.00,
    color: 'Blue',
    intensity: 'vivid',
    clarity: 'ec1',
    certification: 'IGI',
    price: 450,
    currency: '€',
    image: null,
    reportNumber: 'IGI567890'
  },
  {
    id: 'G011',
    type: 'lab',
    gemstoneType: 'ruby',
    shape: 'oval',
    carat: 1.50,
    color: 'Red',
    intensity: 'vivid',
    clarity: 'ec1',
    certification: 'IGI',
    price: 380,
    currency: '€',
    image: null,
    reportNumber: 'IGI567891'
  },
  {
    id: 'G012',
    type: 'lab',
    gemstoneType: 'emerald',
    shape: 'emerald',
    carat: 2.25,
    color: 'Green',
    intensity: 'vivid',
    clarity: 'ec1',
    certification: 'IGI',
    price: 520,
    currency: '€',
    image: null,
    reportNumber: 'IGI567892'
  },
  {
    id: 'G013',
    type: 'natural',
    gemstoneType: 'alexandrite',
    shape: 'cushion',
    carat: 0.85,
    color: 'Color Change',
    intensity: 'medium',
    clarity: 'vs1',
    certification: 'GRS',
    price: 15000,
    currency: '€',
    image: null,
    reportNumber: 'GRS789014'
  },
  {
    id: 'G014',
    type: 'natural',
    gemstoneType: 'opal',
    shape: 'oval',
    carat: 3.75,
    color: 'Multi',
    intensity: 'vivid',
    clarity: 'translucent',
    certification: 'ICL',
    price: 2800,
    currency: '€',
    image: null,
    reportNumber: 'ICL123463'
  },
  {
    id: 'G015',
    type: 'natural',
    gemstoneType: 'pearl',
    shape: 'round',
    carat: 8.5,
    color: 'White',
    intensity: 'light',
    clarity: 'ec1',
    certification: 'ICL',
    price: 1200,
    currency: '€',
    image: null,
    reportNumber: 'ICL123464'
  }
];

// Function to generate more sample data if needed
export function generateMoreDiamonds(count = 50) {
  const shapes = ['round', 'oval', 'cushion', 'princess', 'emerald', 'pear', 'marquise', 'asscher', 'radiant', 'heart'];
  const colors = ['D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L'];
  const clarities = ['FL', 'IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2'];
  const cuts = ['Good', 'Very Good', 'Excellent', 'Ideal'];
  const polishes = ['Good', 'Very Good', 'Excellent'];
  const symmetries = ['Good', 'Very Good', 'Excellent'];
  const fluorescences = ['None', 'Faint', 'Medium', 'Strong'];
  const certifications = ['GIA', 'IGI', 'AGS', 'HRD'];

  const diamonds = [...sampleDiamonds];

  for (let i = 0; i < count; i++) {
    const shape = shapes[Math.floor(Math.random() * shapes.length)];
    const carat = (Math.random() * 4.5 + 0.25).toFixed(2);
    const color = colors[Math.floor(Math.random() * colors.length)];
    const clarity = clarities[Math.floor(Math.random() * clarities.length)];
    const cut = cuts[Math.floor(Math.random() * cuts.length)];

    // Price calculation (simplified)
    const basePrice = parseFloat(carat) * 1000;
    const colorMultiplier = 1 + (colors.indexOf(color) * -0.05);
    const clarityMultiplier = 1 + (clarities.indexOf(clarity) * 0.1);
    const price = Math.round(basePrice * colorMultiplier * clarityMultiplier);

    diamonds.push({
      id: `D${(sampleDiamonds.length + i + 1).toString().padStart(3, '0')}`,
      shape,
      carat: parseFloat(carat),
      color,
      clarity,
      cut,
      polish: polishes[Math.floor(Math.random() * polishes.length)],
      symmetry: symmetries[Math.floor(Math.random() * symmetries.length)],
      fluorescence: fluorescences[Math.floor(Math.random() * fluorescences.length)],
      certification: certifications[Math.floor(Math.random() * certifications.length)],
      price,
      currency: '€',
      lwRatio: shape === 'round' ? 1.0 : (Math.random() * 0.5 + 1.0).toFixed(2),
      image: null,
      reportNumber: `GIA${Math.random().toString().slice(2, 12)}`
    });
  }

  return diamonds;
}
